### ISSUE TITLE
[Question] Date field with date picker

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/gov_uk_date_fields#16]
Is there any guidance on how to setup a date field with a date picker which complies with the Government standards?

**Comment by stephenrichards** [comment]
Sorry, this gem is specifically to generate the html markup for the date entry using three edit boxes (see http://govuk-elements.herokuapp.com/form-elements/example-date/), and integrating it into rails projects.  I don't think GDS standard cover a date-picker because of accessibility issues.
